name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.6 # Dart SDK version
  flutter: 3.16.9 # Flutter SDK version

dependencies:
  url_strategy: ^0.2.0
  image_picker: ^1.0.7
  http: ^1.2.0
  share_plus: ^7.2.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/